### PR TITLE
Fix Mutation Requirement Tooltips

### LINKED ISSUE #21256: NEI shows misleading frugal bee breeding recipe
### Your GTNH Discord Username

_No response_

### Your Pack Version

2.7.2

### Your Server

dxura

### Java Version

Java 21

### Type of Server

Don't know

### Your Expectation

to show this recipe when showing usage of sinister to make frugal. with the right requirements
Image

### The Reality

when searching usage of sinister it shows this requirements, which is wrong 

Image

### Your Proposal

fix wrong recipe

### Final Checklist

- [x] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [x] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [x] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

### PR DESCRIPTION
**Pull request by Ruling-0**
Baited on a quick fix label.

Issue occurs when there are 2 recipes per page, where the special tooltips from the second recipe overwrite the tooltips of the first recipe. Essentially, tooltip rectangles are calculated relative to the recipe, but are checked relative to the whole UI, so this PR adds the recipe offset to the checking part. This also fixes another bug where there were random subtractions in the rectangle check that moved the tooltips to be at the very top of the bee instead of on hovering the chance.

I take the opportunity here to update the buildscript to v2.

Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/21256

### CODE REVIEW

File: src/main/java/hellfirepvp/beebetteratbees/client/gui/BBABGuiRecipeTreeHandler.java [hunk 1]
```diff
@@ -120,7 +124,7 @@ public void drawExtras(int recipe) {
             Map<Rectangle, Collection<String>> boxes = new HashMap<>(4);
             CachedBeeMutationTree.PositionedMutationNodeStack root = cachedTree.getRootStack();
             drawExtrasFrom(root, boxes);
-            this.tipBoxes = boxes;
+            this.tipBoxes.add(recipe, boxes);
```
Comment (UltraProdigy) [inline src/main/java/hellfirepvp/beebetteratbees/client/gui/BBABGuiRecipeTreeHandler.java]: Does NEI protect against an index error here or does it need a guard?

**Review by UltraProdigy — APPROVED** [review]
Possible nit but looks good
